# Generated by Django 4.1.7 on 2023-03-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_data', models.JSONField()),
                ('master_ticket', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
