# Generated by Django 3.2.9 on 2025-09-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfraOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
