# Generated by Django 3.2.9 on 2025-10-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud01', '0003_terraformplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='terraformplan',
            name='run_id',
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
