# Generated by Django 3.2.9 on 2025-10-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud01', '0005_alter_terraformplan_run_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terraformplan',
            name='run_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
