# Generated by Django 5.2.8 on 2025-12-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud01', '0007_alter_terraformplan_run_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='infraoutput',
            name='job_id',
            field=models.CharField(db_index=True, default='legacy', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='infraoutput',
            name='key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='infraoutput',
            name='value',
            field=models.JSONField(default=dict),
        ),
        migrations.AddConstraint(
            model_name='infraoutput',
            constraint=models.UniqueConstraint(fields=('job_id', 'key'), name='uniq_output_per_job_key'),
        ),
    ]
