# Generated by Django 5.2.8 on 2025-12-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud01', '0008_infraoutput_job_id_alter_infraoutput_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildrequest',
            name='requested_build_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='buildrequest',
            name='run_id',
            field=models.CharField(db_index=True, default=-2222, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
