# Generated by Django 5.2.8 on 2026-01-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud01', '0009_buildrequest_requested_build_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildrequest',
            name='destroy_awx_job_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buildrequest',
            name='destroy_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buildrequest',
            name='plan_approval_awx_job_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buildrequest',
            name='plan_approval_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
